version: "3"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host  # Оставляем host mode
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host  # Тоже используем host mode
    restart: unless-stopped
